<?php

$title = "modification de la base de données des groupes chimique | Ceramom BDD";

$etatBdd = "Création d'un groupe chimique";

$content = ""
        . "<div class=\"row\">"
            . "<div class = \"col-sm-7\">"
                . "<h2>LABORATOIRE ARAR</h2>"
                . "<h3><b>$etatBdd</b></h3>"
            . "</div>"
            . "<div class = \"col-sm-5 hidden-xs\">"
                . "<a href=\"http://www.arar.mom.fr/\"><img src = \"../Ressources/Oiseau_Quadri.png\" style=\"width: 200px;\"/></a>"
            . "</div>"
        . "</div>"
        . ""
        . "<div class = \"row\" id = \"advSearch\" style=\"color: #8e3c06;\">"
            . "<h1>Fiche du groupe</h1>"
            . "<form id=\"ficheGroup\" class=\"col-sm-offset-1 col-sm-10 col-lg-10 col-lg-offset-1\" action=\"#\" method=\"get\">"
                
                . "<div class=\"row\" >"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label class=\"\" for=\"gName\">Nom du groupe </label>"
                        . "<br />"
                        . "<input id=\"gName\" class=\"form-control\" type=\"text\" placeholder=\"...\" />"
                    . "</div>"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label class=\"\" for=\"gRef\">Réference</label>"
                        . "<br />"
                        . "<input class=\"form-control\" type=\"text\" placeholder=\"...\" />"
                    . "</div>"
                . "</div>"
                . "<br />"
                . "<div class=\"row\">"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label class=\"\" for=\"selectRegion\">Region </label>"
                        . "<br />"
                        . "<select id=\"selectRegion\" class=\"c-select form-control\"> "
                            . "<option selected>ROME</option>"
                            . "<option selected>Comme moi par exemple !</option>"
                            . "<option selected>Selectionnez une option</option>"
                        . "</select>"                      
                        . ""
                    . "</div>"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label class=\"\" for=\"select3\">Type d'analyse </label>"
                        . "<br />"
                        . "<select id=\"select3\" class=\"c-select form-control\"> "
                        . "<option >Chimie</option>"
                        . "<option >Bino</option>"
                        . "<option >Petro</option>"
                        . "<option >SEM</option>"
                        . "<option >Diffraction</option>"
                        . "<option >Dilato</option>"
                        . "<option >Autre</option>"
                        . "<option selected>Selectionnez une option</option>"
                        . "</select>"
                    . "</div>"
                . "</div>"
        
                . "<br />"
                . "<div class=\"row\">"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label class=\"\" for=\"gDescription\">Description du groupe</label>"
                        . "<textarea id=\"gDescription\" class=\"form-control\"></textarea>"
                        
                        . ""
                    . "</div>"
                    . "<div class=\"col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1\" id=\"selectChi\">"
                        . "<label for=\"freeDesc\">Détails supplémentaires</label>"
                        . "<textarea id=\"freeDesc\" class=\"form-control\"></textarea>"
                    . "</div>"
                . "</div>"
                . "<br />"
                . "<center><button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%;\"><b>Sauvergarder</b></button></center>"
                . "<br />"
            . "</form>"
        . "</div>";

require_once (dirname(dirname(__FILE__)) . "/Vue/layout.php");
